grails-shell-cli requires jansi 1.18 max, forge was providing 2.4.1
1.18 works for grails-shell-cli and grails-forge-cli

Fixes:  Exception: java.lang.NoSuchMethodError thrown from the UncaughtExceptionHandler in thread "main"

https://github.com/apache/grails-core/issues/13752